const routes = {
    home: "/home",
    login: "/login",
    register: "/register",
    createAccount: "/create-account",
    account: "/account",
    productDetail: "/product-detail/:id",
    product: "/products/:id/:search",
    infoOrder: "/info-order",
    checkout: "/checkout",
    order: "/check/order",
    editAddress: "/edit-address/:id",
    editProfile: "/edit-profile/:id",
    updatePassword:"/update-password",
    createAddress: "/create-address",
    seller: "/seller",
    shopProduct: "/shop/products",
    activeAddress: "/shop/address/active",
    addProduct: "/shop/add-product",
    editProduct: "/shop/edit-product/:id",
    orderTrend:"/shop/orders/trend",
    salesOrder:"/shop/orders/sales",
    allOrder: "/shop/orders/all",
    cancelOrder:"/shop/orders/cancel",
    unpaidOrder:"/shop/orders/unpaid",
    processingOrder:"/shop/orders/processing",
    readyOrder:"/shop/orders/ready",
    lastedOrder:"/shop/orders/lasted",
    editShop:"/shop/edit",
    vnpayPayment: "/vnpay-payment",
    allCustomer: "/customers",
    historyOrder: "/orders/history/:email",


};
export default routes;